name: upi_pay_example
description: Demonstrates how to use the upi_pay plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">2.0.0"

dependencies:
  flutter:
    sdk: flutter
  upi_pay:
    path: ../
  cupertino_icons: ^1.0.2
  android_intent: ">=0.3.7+2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
