name: flutter_upi_india
description: A flutter plugin to launch UPI payment applications on Android and iOS towards making UPI payments.
version: 0.0.3

homepage: https://github.com/princeflutterdev/flutter_upi_pay

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">3.0.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^3.0.2
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.trident.flutter_upi_india
        pluginClass: UpiPayPlugin
      ios:
        pluginClass: UpiPayPlugin
  assets:
    - assets/apps/ios/
